gui:
  mouseEvents: true
  language: "en" # one of 'auto' | 'en' | 'zh' | 'pl' | 'nl' | 'ja' | 'ko'
  timeFormat: "2022-11-03 15:04" # https://pkg.go.dev/time#Time.Format
  shortTimeFormat: 15:04
  theme:
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    inactiveViewSelectedLineBgColor:
      - "#313244" # Surface0
      - bold
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red # Red
    defaultFgColor:
      - default
  showRandomTip: false
  showBottomLine: false
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  parseEmoji: true

# Periodic update checks
update:
  method: never

os:
  editPreset: "nvim"

notARepository: "skip" # one of: 'prompt' | 'create' | 'skip' | 'quit'
