#!/bin/sh

# Alias
alias sozsh='source ~/.zshenv && source "$XDG_CONFIG_HOME"/zsh/.zshrc'
alias nv='nvim'
alias vim='vim -i NONE'
# alias cat='/usr/share/vim/vim90/macros/less.sh' # wrapper for bat
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias py='python3'
alias nvf='nvim `fzf`'
alias ls='lsd -l'
# alias ls='eza -1lFaBhHm --git --group-directories-first --no-permissions --octal-permissions --time-style="long-iso" -I=".DS_Store|.CFUserTextEncoding"'
# alias rm='trash' # mv to trash bin
alias lg='lazygit'
alias lzd='lazydocker'
alias CA='conda activate'
alias CD='conda deactivate'
alias tb='tensorboard --logdir'
alias fzz='zoxide query | fzf'
alias fzp='cat /etc/services | fzf'
alias flsof4="lsof -Pni4 | awk '{printf \"%10s %6s %5s %4s %-20s\n\", \$1, \$2, \$3, \$8, \$9}' | fzf --header-lines=1 --cycle"
alias rm='rm -iv'
alias mkdir='mkdir -pv'
alias ps='ps auxf'
alias ping='ping -c 5'
alias less='less -R'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias tree='tree -CAF --dirsfirst'
alias treed='tree -CAFd'
alias cargobin='cargo binstall --no-discover-github-token -y'
alias z='zi' # map z to zoxide interactive selection
alias yz='yazi'
alias nixup='cd $HOME/.config/home-manager && nix flake update && home-manager switch --impure && cd "$OLDPWD"'
# alias nixclean='nix-collect-garbage -d && nix-env --delete-generations old && nix-store --gc && nix-store --optimise'
alias nixclean='nix-collect-garbage -d && nix-store --gc && nix-store --optimise'
alias nixsearch='nix search nixpkgs'
alias docker_restart='docker compose down --remove-orphans && docker compose up -d'

# FIX: restart cloudflared service on macOS to fix ssh login errors
cfd_reload() {
	if [ "$(uname)" = "Darwin" ]; then
		sudo launchctl stop com.cloudflare.cloudflared && sudo launchctl start com.cloudflare.cloudflared
		echo "Darwin/cloudflared reload!"
	elif [ "$(uname)" = "Linux" ]; then
		sudo systemctl restart cloudflared
		echo "Linux/cloudflared reload!"
	else
		echo 'Unknown OS!'
	fi
}

nix_reload() {
	if [ "$(uname)" = "Darwin" ]; then
		sudo launchctl remove org.nixos.nix-daemon && sudo launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist
		echo "Darwin/nix-daemon reload!"
	elif [ "$(uname)" = "Linux" ]; then
		sudo systemctl daemon-reload && sudo systemctl restart nix-daemon
		echo "Linux/nix-daemon reload!"
	else
		echo 'Unknown OS!'
	fi
}

# cd to the previous directory
alias bd='cd "$OLDPWD"'

# yazi shell wrapper
yy() {
	tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ "$cwd" != "" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd" || exit
	fi
	rm -f -- "$tmp"
	unset tmp
}

# show open ports
alias openports='netstat -nape --inet'

# reboot
alias rebootsafe='sudo shutdown -r now'
alias rebootforce='sudo shutdown -r -n now'

# Alias's for archives
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

# vim: set ft=sh :
