#!/usr/bin/env python3
def is_vanilla() -> bool:
    """:return: whether running "vanilla" Python"""
    import sys

    return not hasattr(__builtins__, "__IPYTHON__") and "bpython" not in sys.argv[0]


def setup_history():
    """read and write history from state file"""
    import readline

    # import atexit
    # import os
    # from pathlib import Path

    # if state_home := os.environ.get("XDG_CACHE_HOME"):
    #     state_home = Path(state_home)
    # else:
    #     state_home = Path.home() / ".cache"

    # historyPath = os.path.join(state_home, "python_history")
    # print(historyPath)

    # if not os.path.exists(historyPath):
    #     file = open(historyPath, "w")
    #     file.close()
    # readline.read_history_file(historyPath)
    # atexit.register(readline.write_history_file, historyPath)
    readline.set_auto_history(False)


if is_vanilla():
    setup_history()
