output:
  - "spdx-json=syft.spdx.json"

check-for-app-update: false

parallelism: 4

format:
  json:
    pretty: true
  spdx-json:
    pretty: true
  cyclonedx-json:
    pretty: true
  cyclonedx-xml:
    pretty: true
