# Same as '--format'
format: "spdx-json"

# Same as '--ignore-policy'
ignore-policy: ""

# Same as '--ignorefile'
# ignorefile: ".trivyignore"

# Same as '--list-all-pkgs'
list-all-pkgs: false

# Same as '--output'
output: "./trivy.spdx.json"

# Same as '--output-plugin-arg'
output-plugin-arg: ""

# Same as '--report'
report: "all"

scan:
  # Same as '--compliance'
  compliance: ""

  # Same as '--show-suppressed'
  show-suppressed: false

# Same as '--severity'
severity:
  - UNKNOWN
  - LOW
  - MEDIUM
  - HIGH
  - CRITICAL

image:
  docker:
    # Same as '--docker-host'
    host: ""

  podman:
    # Same as '--podman-host'
    host: ""

  # Same as '--removed-pkgs'
  removed-pkgs: false

  # Same as '--image-src'
  source:
    - docker
    - containerd
    - podman
    - remote

kubernetes:
  # Same as '--burst'
  burst: 10

  # Same as '--disable-node-collector'
  disableNodeCollector: false

  exclude:
    # Same as '--exclude-nodes'
    nodes: []

    # Same as '--exclude-owned'
    owned: false

  # Same as '--exclude-kinds'
  excludeKinds: []

  # Same as '--exclude-namespaces'
  excludeNamespaces: []

  # Same as '--include-kinds'
  includeKinds: []

  # Same as '--include-namespaces'
  includeNamespaces: []

  # Same as '--k8s-version'
  k8s-version: ""

  # Same as '--kubeconfig'
  kubeconfig: ""

  node-collector:
    # Same as '--node-collector-imageref'
    imageref: "ghcr.io/aquasecurity/node-collector:0.3.1"

    # Same as '--node-collector-namespace'
    namespace: "trivy-temp"

  # Same as '--qps'
  qps: 5

  # Same as '--skip-images'
  skipImages: false

  # Same as '--tolerations'
  tolerations: []

license:
  # Same as '--license-confidence-level'
  confidenceLevel: 0.9

  forbidden:
    - AGPL-1.0
    - AGPL-3.0
    - CC-BY-NC-1.0
    - CC-BY-NC-2.0
    - CC-BY-NC-2.5
    - CC-BY-NC-3.0
    - CC-BY-NC-4.0
    - CC-BY-NC-ND-1.0
    - CC-BY-NC-ND-2.0
    - CC-BY-NC-ND-2.5
    - CC-BY-NC-ND-3.0
    - CC-BY-NC-ND-4.0
    - CC-BY-NC-SA-1.0
    - CC-BY-NC-SA-2.0
    - CC-BY-NC-SA-2.5
    - CC-BY-NC-SA-3.0
    - CC-BY-NC-SA-4.0
    - Commons-Clause
    - Facebook-2-Clause
    - Facebook-3-Clause
    - Facebook-Examples
    - WTFPL

  # Same as '--license-full'
  full: false

  # Same as '--ignored-licenses'
  ignored: []

  notice:
    - AFL-1.1
    - AFL-1.2
    - AFL-2.0
    - AFL-2.1
    - AFL-3.0
    - Apache-1.0
    - Apache-1.1
    - Apache-2.0
    - Artistic-1.0-cl8
    - Artistic-1.0-Perl
    - Artistic-1.0
    - Artistic-2.0
    - BSL-1.0
    - BSD-2-Clause-FreeBSD
    - BSD-2-Clause-NetBSD
    - BSD-2-Clause
    - BSD-3-Clause-Attribution
    - BSD-3-Clause-Clear
    - BSD-3-Clause-LBNL
    - BSD-3-Clause
    - BSD-4-Clause
    - BSD-4-Clause-UC
    - BSD-Protection
    - CC-BY-1.0
    - CC-BY-2.0
    - CC-BY-2.5
    - CC-BY-3.0
    - CC-BY-4.0
    - FTL
    - ISC
    - ImageMagick
    - Libpng
    - Lil-1.0
    - Linux-OpenIB
    - LPL-1.02
    - LPL-1.0
    - MS-PL
    - MIT
    - NCSA
    - OpenSSL
    - PHP-3.01
    - PHP-3.0
    - PIL
    - Python-2.0
    - Python-2.0-complete
    - PostgreSQL
    - SGI-B-1.0
    - SGI-B-1.1
    - SGI-B-2.0
    - Unicode-DFS-2015
    - Unicode-DFS-2016
    - Unicode-TOU
    - UPL-1.0
    - W3C-19980720
    - W3C-20150513
    - W3C
    - X11
    - Xnet
    - Zend-2.0
    - zlib-acknowledgement
    - Zlib
    - ZPL-1.1
    - ZPL-2.0
    - ZPL-2.1

  permissive: []

  reciprocal:
    - APSL-1.0
    - APSL-1.1
    - APSL-1.2
    - APSL-2.0
    - CDDL-1.0
    - CDDL-1.1
    - CPL-1.0
    - EPL-1.0
    - EPL-2.0
    - FreeImage
    - IPL-1.0
    - MPL-1.0
    - MPL-1.1
    - MPL-2.0
    - Ruby

  restricted:
    - BCL
    - CC-BY-ND-1.0
    - CC-BY-ND-2.0
    - CC-BY-ND-2.5
    - CC-BY-ND-3.0
    - CC-BY-ND-4.0
    - CC-BY-SA-1.0
    - CC-BY-SA-2.0
    - CC-BY-SA-2.5
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - GPL-1.0
    - GPL-2.0
    - GPL-2.0-with-autoconf-exception
    - GPL-2.0-with-bison-exception
    - GPL-2.0-with-classpath-exception
    - GPL-2.0-with-font-exception
    - GPL-2.0-with-GCC-exception
    - GPL-3.0
    - GPL-3.0-with-autoconf-exception
    - GPL-3.0-with-GCC-exception
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
    - NPL-1.0
    - NPL-1.1
    - OSL-1.0
    - OSL-1.1
    - OSL-2.0
    - OSL-2.1
    - OSL-3.0
    - QPL-1.0
    - Sleepycat

  unencumbered:
    - CC0-1.0
    - Unlicense
    - 0BSD

pkg:
  # Same as '--include-dev-deps'
  include-dev-deps: false

  # Same as '--pkg-relationships'
  relationships:
    - unknown
    - root
    - workspace
    - direct
    - indirect

  # Same as '--pkg-types'
  types:
    - os
    - library

registry:
  mirrors:

  # Same as '--password'
  password: []

  # Same as '--password-stdin'
  password-stdin: false

  # Same as '--registry-token'
  token: ""

  # Same as '--username'
  username: []

cache:
  # Same as '--cache-dir'
  dir: "~/.cache/trivy"
  # Same as '--cache-backend'
  backend: "fs"

  redis:
    # Same as '--redis-ca'
    ca: ""

    # Same as '--redis-cert'
    cert: ""

    # Same as '--redis-key'
    key: ""

    # Same as '--redis-tls'
    tls: false

  # Same as '--cache-ttl'
  ttl: 0s

clean:
  # Same as '--all'
  all: false

  # Same as '--checks-bundle'
  checks-bundle: false

  # Same as '--java-db'
  java-db: false

  # Same as '--scan-cache'
  scan-cache: false

  # Same as '--vex-repo'
  vex-repo: false

  # Same as '--vuln-db'
  vuln-db: false
